baseURL = 'https://astropi-hackathon.org/'
languageCode = 'en-US'
title = 'AstroPi Hackathon'
uglyURLs = "false"
enableEmoji = "true"
[params]
    description = "Oficiální stránky AstroPi Hackathonu"
[menus]
    [[menu.main]]
        identifier = "aktualni-rocnik"
        name = "Aktuální ročník"
        url = "/aktualni-rocnik"
        weight = "1"
    [[menu.main]]
        identifier = "minule-rocniky"
        name = "Minulé ročníky"
        url = "/minule-rocniky"
        weight = "2"
    [[menu.main]]
        identifier = "novinky"
        name = "Novinky"
        url = "/novinky"
        weight = "3"
    [[menu.main]]
        identifier = "astropi"
        name = "AstroPi"
        url = "/astropi"
        weight = "4"
    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/kontakt"
        weight = "5"